/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sean
 */
public class Desserts extends global {

	// Variables declaration
    private javax.swing.JButton brownieButton;
    private javax.swing.JLabel browniePriceLabel;
    private javax.swing.JButton cakeButton;
    private javax.swing.JLabel cakePriceLabel;
    private javax.swing.JButton cookieButton;
    private javax.swing.JLabel cookiePriceLabel;
    private javax.swing.JLabel dessertsLabel;
    private javax.swing.JButton iceCreamButton;
    private javax.swing.JLabel iceCreamPriceLabel;
    private javax.swing.JButton mainMenuButton;
    public int iceCream;
    public int brownie;
    public int cookie;
    public int cake;
    // End of variables declaration
    
    /**
     * Creates new form Desserts
     */
    public Desserts() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
        dessertsLabel = new javax.swing.JLabel();
        iceCreamButton = new javax.swing.JButton();
        brownieButton = new javax.swing.JButton();
        cookieButton = new javax.swing.JButton();
        cakeButton = new javax.swing.JButton();
        mainMenuButton = new javax.swing.JButton();
        cakePriceLabel = new javax.swing.JLabel();
        cookiePriceLabel = new javax.swing.JLabel();
        browniePriceLabel = new javax.swing.JLabel();
        iceCreamPriceLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dessertsLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        dessertsLabel.setText("Desserts");

        iceCreamButton.setText("Ice Cream");

        brownieButton.setText("Brownie");

        cookieButton.setText("Cookie");

        cakeButton.setText("Cake");

        mainMenuButton.setText("Main Menu");
        mainMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuButtonActionPerformed(evt);
            }
        });

        cakePriceLabel.setText("- - - - - - - - - - - - - - - - - - - - -$2.00");

        cookiePriceLabel.setText("- - - - - - - - - - - - - - - - - - - - -$2.00");

        browniePriceLabel.setText("- - - - - - - - - - - - - - - - - - - - -$2.00");

        iceCreamPriceLabel.setText("- - - - - - - - - - - - - - - - - - - - -$2.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iceCreamButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(brownieButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cookieButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cakeButton, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iceCreamPriceLabel)
                            .addComponent(browniePriceLabel)
                            .addComponent(cookiePriceLabel)
                            .addComponent(cakePriceLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(dessertsLabel)))
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainMenuButton)
                .addGap(36, 36, 36))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {brownieButton, cakeButton, cookieButton, iceCreamButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dessertsLabel)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iceCreamButton)
                    .addComponent(iceCreamPriceLabel))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(browniePriceLabel)
                    .addComponent(brownieButton))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cookiePriceLabel)
                    .addComponent(cookieButton))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cakePriceLabel)
                    .addComponent(cakeButton))
                .addGap(31, 31, 31)
                .addComponent(mainMenuButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {brownieButton, cakeButton, cookieButton, iceCreamButton});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButtonActionPerformed
        // This button brings the user back to the main menu
        new MainMenuGui().setVisible(true);
        new Desserts().setVisible(false);
    }
    private void iceCreamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButtonActionPerformed
        // This button adds one pizza to the cutomers order
        iceCream+=1;
        price+=2;
        reciept.setText("+\nCoke- - - - - - - - - - - - - - - - - - - - -$2.00");
    }
    private void brownieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButtonActionPerformed
        // This button adds one pizza to the cutomers order
        brownie+=1;
        price+=3;
        reciept.setText("+\nPepsi- - - - - - - - - - - - - - - - - - - - -$2.00");
    }
    private void cookieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButtonActionPerformed
        // This button adds one pizza to the cutomers order
        cookie+=1;
        price+=4;  
        reciept.setText("+\nPowerade- - - - - - - - - - - - - - - - - - - - -$2.00");
    }
    private void cakeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButtonActionPerformed
        // This button adds one pizza to the cutomers order
        cake+=1;
        price+=5;  
        reciept.setText("+\nGatorade- - - - - - - - - - - - - - - - - - - - -$2.00");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Desserts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Desserts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Desserts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desserts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Desserts().setVisible(true);
            }
        });
    }

    
}
