
public class Drinks extends global {

	// Variables declaration
    private javax.swing.JButton cokeButton;
    private javax.swing.JLabel cokePriceLabel;
    private javax.swing.JLabel drinksLabel;
    private javax.swing.JButton gatoradeButton;
    private javax.swing.JLabel gatoradePriceLabel;
    private javax.swing.JButton mainMenuButton;
    private javax.swing.JButton pepsiButton;
    private javax.swing.JLabel pepsiPriceLabel;
    private javax.swing.JButton poweradeButton;
    private javax.swing.JLabel poweradePriceLabel;
    public int coke;
    public int pepsi;
    public int powerade;
    public int gatorade;
    // End of variables declaration
    
    /**
     * Creates new form Drinks
     */
    public Drinks() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        drinksLabel = new javax.swing.JLabel();
        cokeButton = new javax.swing.JButton();
        pepsiButton = new javax.swing.JButton();
        poweradeButton = new javax.swing.JButton();
        gatoradeButton = new javax.swing.JButton();
        mainMenuButton = new javax.swing.JButton();
        gatoradePriceLabel = new javax.swing.JLabel();
        poweradePriceLabel = new javax.swing.JLabel();
        pepsiPriceLabel = new javax.swing.JLabel();
        cokePriceLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        drinksLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        drinksLabel.setText("Drinks");

        cokeButton.setText("Coke");

        pepsiButton.setText("Pepsi");

        poweradeButton.setText("Powerade");

        gatoradeButton.setText("Gatorade");

        mainMenuButton.setText("Main Menu");
        mainMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuButtonActionPerformed(evt);
            }
        });

        gatoradePriceLabel.setText("- - - - - - - - - - - - - - - - - - - - -$2.00");

        poweradePriceLabel.setText("- - - - - - - - - - - - - - - - - - - - -$2.00");

        pepsiPriceLabel.setText("- - - - - - - - - - - - - - - - - - - - -$2.00");

        cokePriceLabel.setText("- - - - - - - - - - - - - - - - - - - - -$2.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cokeButton)
                            .addComponent(pepsiButton)
                            .addComponent(gatoradeButton)
                            .addComponent(poweradeButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cokePriceLabel)
                            .addComponent(pepsiPriceLabel)
                            .addComponent(poweradePriceLabel)
                            .addComponent(gatoradePriceLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(drinksLabel)))
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainMenuButton)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(drinksLabel)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cokeButton)
                    .addComponent(cokePriceLabel))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pepsiPriceLabel)
                    .addComponent(pepsiButton))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(poweradePriceLabel)
                    .addComponent(poweradeButton))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gatoradePriceLabel)
                    .addComponent(gatoradeButton))
                .addGap(31, 31, 31)
                .addComponent(mainMenuButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButtonActionPerformed
        // This button brings the user back to the main menu
        new MainMenuGui().setVisible(true);
        new Entree().setVisible(false);
    }
    private void cokeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButtonActionPerformed
        // This button adds one pizza to the cutomers order
        coke+=1;
        price+=2;
        reciept.setText("+\nCoke- - - - - - - - - - - - - - - - - - - - -$2.00");
    }
    private void pepsiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButtonActionPerformed
        // This button adds one pizza to the cutomers order
        pepsi+=1;
        price+=3;
        reciept.setText("+\nPepsi- - - - - - - - - - - - - - - - - - - - -$2.00");
    }
    private void poweradeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButtonActionPerformed
        // This button adds one pizza to the cutomers order
        powerade+=1;
        price+=4;  
        reciept.setText("+\nPowerade- - - - - - - - - - - - - - - - - - - - -$2.00");
    }
    private void gatoradeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButtonActionPerformed
        // This button adds one pizza to the cutomers order
        gatorade+=1;
        price+=5;  
        reciept.setText("+\nGatorade- - - - - - - - - - - - - - - - - - - - -$2.00");
    }
  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Drinks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Drinks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Drinks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Drinks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Drinks().setVisible(true);
            }
        });
    }

    
}
