
/**
 *
 * @author Sean
 */
public class MainMenuGui extends global{

	// Variables declaration
	private javax.swing.JLabel MainMenuTitle;
    private javax.swing.JButton dessertsButton;
    private javax.swing.JButton drinksButton;
    private javax.swing.JButton entreeButton;
    private javax.swing.JButton finishButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JScrollPane jScrollPane1;
    //public javax.swing.JTextArea reciept;
    private javax.swing.JButton sidesButton;
    private javax.swing.JButton signOutButton;
    public int price;
    // End of variables declaration
    
    /**
     * Creates new form MainMenuGui
     */
    public MainMenuGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainMenuTitle = new javax.swing.JLabel();
        entreeButton = new javax.swing.JButton();
        sidesButton = new javax.swing.JButton();
        drinksButton = new javax.swing.JButton();
        dessertsButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        reciept = new javax.swing.JTextArea();
        finishButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        signOutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainMenuTitle.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        MainMenuTitle.setText("Sean's Restaurant of Awesomeness");

        entreeButton.setText("Entrees");
        entreeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entreeButtonActionPerformed(evt);
            }
        });

        sidesButton.setText("Sides");
        sidesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sidesButtonActionPerformed(evt);
            }
        });

        drinksButton.setText("Drinks");
        drinksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinksButtonActionPerformed(evt);
            }
        });

        dessertsButton.setText("Desserts");
        dessertsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dessertsButtonActionPerformed(evt);
            }
        });

        reciept.setColumns(20);
        reciept.setRows(5);
        jScrollPane1.setViewportView(reciept);

        finishButton.setText("Finish and Pay");

        resetButton.setText("Reset order");

        signOutButton.setText("Sign Out");
        signOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MainMenuTitle)
                .addGap(82, 82, 82))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(drinksButton)
                            .addComponent(entreeButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dessertsButton)
                            .addComponent(sidesButton)))
                    .addComponent(signOutButton))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(finishButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resetButton))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dessertsButton, drinksButton, entreeButton, sidesButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainMenuTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(entreeButton)
                        .addGap(18, 18, 18)
                        .addComponent(drinksButton)
                        .addGap(28, 28, 28)
                        .addComponent(signOutButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sidesButton)
                        .addGap(18, 18, 18)
                        .addComponent(dessertsButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finishButton)
                    .addComponent(resetButton))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dessertsButton, drinksButton, entreeButton, sidesButton});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entreeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entreeButtonActionPerformed
        // This button brings up the entree selection menu
        new MainMenuGui().setVisible(false);
        new Entree().setVisible(true);
    }//GEN-LAST:event_entreeButtonActionPerformed

    private void sidesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sidesButtonActionPerformed
        // This button brings the user to the sides menu
        new MainMenuGui().setVisible(false);
        new Entree().setVisible(true);
    }//GEN-LAST:event_sidesButtonActionPerformed

    private void drinksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinksButtonActionPerformed
        // This button brings the user to the drinks menu
        new MainMenuGui().setVisible(false);
        new Drinks().setVisible(true);
    }//GEN-LAST:event_drinksButtonActionPerformed

    private void dessertsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dessertsButtonActionPerformed
        // This button brings the user to the dessert menu
        new MainMenuGui().setVisible(false);
        new Desserts().setVisible(true);
    }//GEN-LAST:event_dessertsButtonActionPerformed

    private void signOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutButtonActionPerformed
        // This button exits the program and returns the user to the authentication screen
        new MainMenuGui().setVisible(false);
        new NewJFrame().setVisible(true);
    }//GEN-LAST:event_signOutButtonActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuGui().setVisible(true);
            }
        });
    }
   
    
}
