/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sean
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public final String authentication = "1234";
    public String pinInput;
    public String input;
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pinButton1 = new javax.swing.JButton();
        pinButton2 = new javax.swing.JButton();
        pinButton3 = new javax.swing.JButton();
        pinButton4 = new javax.swing.JButton();
        pinButton5 = new javax.swing.JButton();
        pinButton6 = new javax.swing.JButton();
        pinButton7 = new javax.swing.JButton();
        pinButton8 = new javax.swing.JButton();
        pinButton9 = new javax.swing.JButton();
        pinButton0 = new javax.swing.JButton();
        pinButtonClear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pinTextField = new javax.swing.JTextField();
        pinButtonEnter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pinButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        pinButton1.setText("1");
        pinButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinButton1ActionPerformed(evt);
            }
        });

        pinButton2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        pinButton2.setText("2");
        pinButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinButton2ActionPerformed(evt);
            }
        });

        pinButton3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        pinButton3.setText("3");
        pinButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinButton3ActionPerformed(evt);
            }
        });

        pinButton4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        pinButton4.setText("4");
        pinButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinButton4ActionPerformed(evt);
            }
        });

        pinButton5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        pinButton5.setText("5");
        pinButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinButton5ActionPerformed(evt);
            }
        });

        pinButton6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        pinButton6.setText("6");
        pinButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinButton6ActionPerformed(evt);
            }
        });

        pinButton7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        pinButton7.setText("7");
        pinButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinButton7ActionPerformed(evt);
            }
        });

        pinButton8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        pinButton8.setText("8");
        pinButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinButton8ActionPerformed(evt);
            }
        });

        pinButton9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        pinButton9.setText("9");
        pinButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinButton9ActionPerformed(evt);
            }
        });

        pinButton0.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        pinButton0.setText("0");
        pinButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinButton0ActionPerformed(evt);
            }
        });

        pinButtonClear.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        pinButtonClear.setText("Clear");
        pinButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinButtonClearActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Please Enter Employee PIN");

        pinButtonEnter.setText("Enter");
        pinButtonEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinButtonEnterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pinButton4)
                        .addGap(11, 11, 11)
                        .addComponent(pinButton5)
                        .addGap(12, 12, 12)
                        .addComponent(pinButton6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pinButton1)
                        .addGap(11, 11, 11)
                        .addComponent(pinButton2)
                        .addGap(12, 12, 12)
                        .addComponent(pinButton3))
                    .addComponent(jLabel1)
                    .addComponent(pinTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pinButtonClear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pinButton0))
                            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                                .addComponent(pinButton7)
                                .addGap(11, 11, 11)
                                .addComponent(pinButton8)))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pinButton9)
                            .addComponent(pinButtonEnter))))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {pinButton0, pinButton1, pinButton2, pinButton3, pinButton4, pinButton5, pinButton6, pinButton7, pinButton8, pinButton9, pinButtonClear, pinButtonEnter});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pinButton1)
                    .addComponent(pinButton2)
                    .addComponent(pinButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pinButton4)
                    .addComponent(pinButton5)
                    .addComponent(pinButton6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pinButton7)
                    .addComponent(pinButton8)
                    .addComponent(pinButton9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pinButton0)
                    .addComponent(pinButtonClear)
                    .addComponent(pinButtonEnter))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {pinButton0, pinButton1, pinButton2, pinButton3, pinButton4, pinButton5, pinButton6, pinButton7, pinButton8, pinButton9, pinButtonClear, pinButtonEnter});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pinButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinButton1ActionPerformed
        // This method concatanates 1 onto the pin entry
        pinInput +="1";
        input=pinTextField.getText();
        pinTextField.setText(input+"*");
    }//GEN-LAST:event_pinButton1ActionPerformed

    private void pinButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinButton2ActionPerformed
        // This method concatanates 2 onto the pin entry
        pinInput +="2";
        input=pinTextField.getText();
        pinTextField.setText(input+"*");
    }//GEN-LAST:event_pinButton2ActionPerformed

    private void pinButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinButton3ActionPerformed
        // This method concatanates 3 onto the pin entry
        pinInput +="3";
        input=pinTextField.getText();
        pinTextField.setText(input+"*");
    }//GEN-LAST:event_pinButton3ActionPerformed

    private void pinButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinButton4ActionPerformed
        // This method concatanates 4 onto the pin entry
        pinInput +="4";
        input=pinTextField.getText();
        pinTextField.setText(input+"*");
    }//GEN-LAST:event_pinButton4ActionPerformed

    private void pinButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinButton5ActionPerformed
        // This method concatanates 5 onto the pin entry
        pinInput +="5";
        input=pinTextField.getText();
        pinTextField.setText(input+"*");
    }//GEN-LAST:event_pinButton5ActionPerformed

    private void pinButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinButton6ActionPerformed
        // This method concatanates 6 onto the pin entry
        pinInput +="6";
        input=pinTextField.getText();
        pinTextField.setText(input+"*");
    }//GEN-LAST:event_pinButton6ActionPerformed

    private void pinButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinButton7ActionPerformed
        // This method concatanates 7 onto the pin entry
        pinInput +="7";
        input=pinTextField.getText();
        pinTextField.setText(input+"*");
    }//GEN-LAST:event_pinButton7ActionPerformed

    private void pinButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinButton8ActionPerformed
        // This method concatanates 8 onto the pin entry
        pinInput +="8";
        input=pinTextField.getText();
        pinTextField.setText(input+"*");
    }//GEN-LAST:event_pinButton8ActionPerformed

    private void pinButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinButton9ActionPerformed
        // This method concatanates 9 onto the pin entry
        pinInput +="9";
        input=pinTextField.getText();
        pinTextField.setText(input+"*");
    }//GEN-LAST:event_pinButton9ActionPerformed

    private void pinButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinButton0ActionPerformed
        // This method concatanates 0 onto the pin entry
        pinInput +="0";
        input=pinTextField.getText();
        pinTextField.setText(input+"*");
    }//GEN-LAST:event_pinButton0ActionPerformed

    private void pinButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinButtonClearActionPerformed
        // This method resets the pin input
        pinInput ="";
        pinTextField.setText("");
    }//GEN-LAST:event_pinButtonClearActionPerformed

    private void pinButtonEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinButtonEnterActionPerformed
        // This button tries to authenticate the user via pin
        if(pinInput.equals("1234"))
        {
            //set the panel to false and bring up the entry panel
            pinTextField.setText("User Authenticated.");
            new NewJFrame().setVisible(false);
            new MainMenuGui().setVisible(true);
        }
        else
        {
            pinTextField.setText("Failed Authentication. Try again.");
        }
    }//GEN-LAST:event_pinButtonEnterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton pinButton0;
    private javax.swing.JButton pinButton1;
    private javax.swing.JButton pinButton2;
    private javax.swing.JButton pinButton3;
    private javax.swing.JButton pinButton4;
    private javax.swing.JButton pinButton5;
    private javax.swing.JButton pinButton6;
    private javax.swing.JButton pinButton7;
    private javax.swing.JButton pinButton8;
    private javax.swing.JButton pinButton9;
    private javax.swing.JButton pinButtonClear;
    private javax.swing.JButton pinButtonEnter;
    private javax.swing.JTextField pinTextField;
    // End of variables declaration//GEN-END:variables
}
